---
title: "R Notebook"
output: html_notebook
---

Graduation rate data comes from the [North Carolina DPI website](http://www.ncpublicschools.org/accountability/reporting/cohortgradrate).

```{r}
# loabd libraries
library(tidyverse)
library(rstanarm)
```

```{r}
# import data
grad_rates <- read_csv('grad_rates.csv') %>%
  # data currently only has columns for total number of students and percentage grads
  # create columns for number of grads and number of non-grads
  mutate(grads = round(total*percent, 0),
         non_grads = total-grads)

# data has economically disadvantaged rates, but not rates for non-economically disadvantaged
# create this category by using total and economically disadvantages
eds <- grad_rates %>%
  filter(group == 'EDS')
all <- grad_rates %>%
  filter(group == 'ALL')

# create function to calculate non-eds values by subtracting total from eds
non_eds_values <- function(col_name) {
  return(all[[col_name]] - eds[[col_name]])
}

# create dataframe for non_eds
non_eds <- data.frame(year = all$year,
                      district = all$district,
                      group = rep('NON_EDS', nrow(all)),
                      total = non_eds_values('total'),
                      grads = non_eds_values('grads'),
                      non_grads = non_eds_values('non_grads')) %>%
  mutate(percent = grads /total)

# bind non-EDS to regular dataframe
grad_rates <- grad_rates %>%
  bind_rows(non_eds) %>%
  # create combined column of year, county, and ethnicity for model 
  mutate(level = paste(year, district, group, sep = ' ')) %>%
  # sort by district, year, and demographic
  arrange(district, year, group)
  
```

```{r}
# create model with one level that combines county, year, and demographic

SEED <- 101
wi_prior <- normal(-1, 1)  # weakly informative prior on log-odds

fit <- stan_glmer(cbind(grads, non_grads) ~ (1 | level), data = grad_rates, 
             family = binomial("logit"),
             prior_intercept = wi_prior, seed = SEED)

fit_trace <- as.data.frame(fit)

c('Intercept', )
```

