---
title: "Description of employment variables"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
# prevent printing or R code in the output
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      echo = FALSE)
```

```{r import}
 # import functions and packages
library(tidyverse)
library(knitr)
# load custom ACS functions
source('../../functions/acs/acs_functions_test.R')

```

This script simply outputs the variable descriptions.

```{r}
read_csv('data/employment_all_years_counties.csv') %>%
  # from counties, remove 'county, North Carolina';
  # this will make it easier to filter based on counties
  mutate(geo_description = str_replace(geo_description, " County, North Carolina", "")) %>%
  # we only need rows representing the employment rate
  # these rows have the phrase 'Employed;' or 'Employment/Population Ratio' in the description
  # change the description so all rows have phrase 'Employment/Population Ratio'; which is the most recent phrase
  mutate(description = str_replace(.$description, 'Employed; ', 'Employment/Population Ratio; ')) %>%
  filter(str_detect(description, 'Employment[/]Population Ratio;')) %>%
  select(label, description) %>%
  distinct() %>%
  kable()
```