---
title: "Gender Income Inequality"
output: html_document
---

```{r setup, include=FALSE}
# prevent printing or R code in the output
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r import}
library(plotly)
# import function; must mvoe back one folder
source('../acs_functions.R')

# import data 
gender_inequality <- read_csv('data/gender_pay.csv') %>%
  # only keep needed ethnicities
  ff_ethnicity() %>%
  # add lower and upper confidence intervals
  mutate(lower_ci = estimate - moe,
         upper_ci = estimate + moe)
```

```{r}
# calculate gender income ratio for each comparison city, using all races and separating by year

# create separate columns for male and female rates, so ratios can be calculated
# also add confidence intervals

# create male dataset
gender_inequality_male <-  gender_inequality %>%
  # only keep rows for males that worked 12 months (003)
  ff_keep_vars('003') %>%
  # remane variabels to signify it is from males
  rename(m_estimate = estimate, m_moe = moe,
         m_lower_ci = lower_ci, m_upper_ci = upper_ci) %>%
  # only keep needed variables
  select(NAME, m_estimate, m_moe, m_lower_ci, m_upper_ci, year, ethnicity)
  

# create female dataset
gender_inequality_female <-  gender_inequality %>%
  # only keep rows for females that worked 12 months (006)
  ff_keep_vars('006') %>%
  # remane variabels to signify it is from females
  rename(f_estimate = estimate, f_moe = moe,
         f_lower_ci = lower_ci, f_upper_ci = upper_ci) %>%
  # only keep needed variables
  select(NAME, f_estimate, f_moe, f_lower_ci, f_upper_ci, year, ethnicity)

# join male and female datasets
gender_inequality_sex <- left_join(gender_inequality_male, gender_inequality_female,
                                   by = c('NAME', 'year', 'ethnicity'))

# calculate income ratios and MOE
gender_inequality_sex <- ff_ratios(gender_inequality_sex, 'f_estimate', 'f_moe', 'm_estimate', 'm_moe')
```

[Enter text describing trends through time and comparisons between geographic units.]

```{r}
# create line chart of ratios by year and geographic unit

gender_inequality_sex %>%
  filter(ethnicity == 'ALL') %>%
  plot_ly(x=~year, y=~ratio, split=~NAME,
          type="scatter",color=~NAME, mode="lines+markers",
          hoverinfo='text', 
          text = ~paste('</br> County: ', NAME,
                        '</br> Year: ', year,
                        '</br> Ratio: ', round(ratio,2),
                        '</br> 95% Margin of error: ', round(ratio_moe,2))) %>%
    layout(yaxis = list(title = 'Female to male income ratio'))

# add_ribbons(
#               ymin = ~ratio - ratio_moe,
#               ymax = ~ratio + ratio_moe,
#               name = "95% Confidence Interval")
```

[Enter text describing demographic issues here]

```{r}
gender_inequality_sex %>%
  # filter for most recent year and remove 'ALL' rethnicities category
  filter((year == max(.$year)) & (ethnicity != 'ALL')) %>%
  plot_ly(x = ~ethnicity, y = ~ratio, color = ~NAME,
          type = 'bar',
          hoverinfo='text', 
          text = ~paste('</br> County: ', NAME,
                        '</br> Ratio: ', round(ratio,2),
                        '</br> 95% Margin of error: ', round(ratio_moe,2)))
```