---
title: "Gender income inequality"
output:
  html_document:
    df_print: paged
---
---

```{r setup, include=FALSE}
# prevent printing or R code in the output
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE)
```

```{r import}
 # import functions and packages
library(tidyverse)
library(tidycensus)
library(plotly)
# load custom ACS functions
source('../functions/acs_load_funcs.R')

```

```{r}
# import data 
gender_inequality <- read_csv('data/gender_pay.csv') %>%
  # only keep needed ethnicities
  ff_acs_ethnicity() %>%
  # add lower and upper confidence intervals
  mutate(lower_ci = estimate - moe,
         upper_ci = estimate + moe)
```

```{r}
# calculate gender income ratio for each comparison city, using all races and separating by year

# create separate columns for male and female rates, so ratios can be calculated
# also add confidence intervals

# create male dataset
gender_inequality_male <-  gender_inequality %>%
  # only keep rows for males that worked 12 months (003)
  ff_acs_keep_vars('003') %>%
  # remane variabels to signify it is from males
  rename(m_estimate = estimate, m_moe = moe,
         m_lower_ci = lower_ci, m_upper_ci = upper_ci) %>%
  # only keep needed variables
  select(NAME, m_estimate, m_moe, m_lower_ci, m_upper_ci, year, ethnicity)
  

# create female dataset
gender_inequality_female <-  gender_inequality %>%
  # only keep rows for females that worked 12 months (006)
  ff_acs_keep_vars('006') %>%
  # remane variabels to signify it is from females
  rename(f_estimate = estimate, f_moe = moe,
         f_lower_ci = lower_ci, f_upper_ci = upper_ci) %>%
  # only keep needed variables
  select(NAME, f_estimate, f_moe, f_lower_ci, f_upper_ci, year, ethnicity)

# join male and female datasets
gender_inequality_sex <- left_join(gender_inequality_male, gender_inequality_female,
                                   by = c('NAME', 'year', 'ethnicity'))

# calculate income ratios and MOE
gender_inequality_sex <- ff_acs_ratios(gender_inequality_sex, 'f_estimate', 'f_moe', 'm_estimate', 'm_moe')
```

[Enter text describing trends through time and comparisons between geographic units.]

```{r}
# create line chart of ratios by year and geographic unit

gender_inequality_sex %>%
  filter(ethnicity == 'ALL') %>%
  ggplot(aes(year, ratio, color = NAME)) +
    geom_line() +
    labs(title = 'Female to male income ratio',
         color = 'Comparison Unit') +
    theme_minimal()
```

[Enter text describing gender income differences in Forsyth through time.]

```{r}
gender_inequality_sex %>%
  # only keep all category of ethnicity
  filter(ethnicity == 'ALL',
         # only keep forsyth county
         str_detect(NAME, 'Forsyth')) %>%
  ggplot(aes(year)) +
    geom_line(aes(y =  f_estimate, color='coral1')) +
    geom_line(aes(y = m_estimate, color='skyblue1')) +
    labs(title = 'Female and male median incomes in Forsyth County',
         y = 'Median income',
         color='Gender') +
   scale_color_manual(labels = c("Female", "Male"), values = c("skyblue1", "coral1")) +
  theme_minimal()
```



[Enter text describing demographic issues here]

```{r}
gender_inequality_sex %>%
  # filter for most recent year and remove 'ALL' ethnicities category
  filter((year == max(.$year)) & (ethnicity != 'ALL')) %>%
  ggplot(aes(ethnicity, ratio, fill=NAME)) +
    geom_bar(stat='identity', position='dodge') +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```