---
title: "Electoral Participation"
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
# set value of whether the file is for an analyst, and therefore all resutls and code blocks are needed,
# or whether the file is for another, and some results and all code blocks are hidden
for_analyst <- TRUE

# global options for code blocks
knitr::opts_chunk$set(warning = FALSE, # supress warnings
                      message = FALSE, # supress messages
                      # do not print out code blocks if for_analyst equals FALSE
                      echo = FALSE)
                      #echo = ifelse(for_analyst == FALSE, FALSE, TRUE))

# value that sets the 'include' parameter in Markdown based on whether the document is for the analyst
to_include = ifelse(for_analyst == TRUE, TRUE, FALSE)
```

```{r import}
# import functions and packages
library(tidyverse)
library(knitr)
library(DT)
library(tidycensus)
# load custom ACS functions
source('../../functions/acs_load_funcs.R')
```


```{r}

df <- voter_history %>%
        #select(1,5,4,20,19,24,12,17)%>%
        mutate(gender = ifelse(gender=='F', 'Female', ifelse(gender=='M', 'Male','Unspecified')))%>%
        mutate(ethnicity = ifelse(gender=='NL', 'non-Latino', ifelse(ethnicity=='HL', 'Hispanic/Latino','Unspecified')))%>%
        mutate(race = ifelse(race=='B', 'African American', ifelse(race=='W', 'White, non_Hispanic', ifelse(race=='I', 'American Indian', ifelse(race=='M', 'Multi Racial', ifelse(race=='O', 'Other', ifelse(race=='A', 'Asian', 'Unspecified')))))))%>%
        rename(age = 'age')%>%
        filter(election.name == '11/04/2008 GENERAL'| election.name =='05/04/2010 PRIMARY' | election.name == '11/02/2010 GENERAL'|election.name == '05/08/2012 PRIMARY'|election.name == '11/06/2012 GENERAL'| election.name == '05/06/2014 PRIMARY'| election.name == '11/04/2014 GENERAL'|election.name == '03/15/2016 PRIMARY'|election.name == '11/08/2016 GENERAL')

election <- df %>%
        group_by(election.name)%>%
        summarize(count = n())%>%
        mutate(type = 'total', subtype = 'total')

gender <- df %>%
        group_by(election.name, gender)%>%
        summarize(count = n())%>%
        mutate(type = 'gender')%>%
        rename('subtype' = gender)
        
ethnicity <- df %>%
        group_by(election.name, ethnicity)%>%
        summarize(count = n())%>%
        mutate(type = 'race')%>%
        rename('subtype' = ethnicity)%>%
        filter(subtype=='Hispanic/Latino')

race <- df %>%
        filter(ethnicity != 'Hispanic/Latino')%>%
        group_by(election.name, race)%>%
        summarize(count = n())%>%
        mutate(type = 'race')%>%
        rename('subtype' = race)

party <- df %>%
        group_by(election.name, party)%>%
        summarize(count = n())%>%
        mutate(type = 'party')%>%
        rename('subtype' = party)

age <- df %>%
        mutate(age = ifelse(age <= 25 | age == 118, '18 to 25', ifelse(age > 25 & age <= 29, '26 to 29', ifelse(age > 29 & age <= 39, '30 to 39', ifelse((age > 39 & age <= 49), '40 to 49', ifelse(age > 49 & age <= 64, '50 to 64', ifelse(age > 64 & age <= 84, '65 to 84', ifelse(age > 84 & age <= 99, '85 to 99', 'NA' ))))))))%>%
        group_by(election.name,age)%>%
        summarize(count = n())%>%
        mutate(type = 'age')%>%
        mutate(year = str_sub(election.name,7,10))%>%
        rename('subtype' = age)

precinct <- df %>%
        group_by(election.name,precinct)%>%
        summarize(count = n())%>%
        mutate(type = 'precinct')%>%
        rename('subtype' = precinct)
        
precinct$subtype <- as.character(precinct$subtype)

ward <- df %>%
        group_by(election.name, ward)%>%
        summarize(count = n())%>%
        mutate(type = 'ward')%>%
        rename('subtype' = ward)
                                                                                              

voted <- bind_rows(election, gender,ethnicity, race, party, age, precinct, ward)%>%
        mutate(geography = 'Forsyth County, NC', year = str_sub(election.name,7,10))

voted <- voted %>%
        mutate(subtype = replace(subtype, str_detect(subtype, "White"), "White, non-Hispanic")) %>%
        mutate(election.name = replace(election.name, str_detect(election.name, "11/04/2008 GENERAL"), "2008/11/04 GENERAL"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "03/15/2016 PRIMARY"), "2016/03/15 PRIMARY"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "05/04/2010 PRIMARY"), "2010/05/04 PRIMARY"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "05/06/2014 PRIMARY"), "2014/05/06 PRIMARY"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "05/08/2012 PRIMARY"), "2012/05/08 PRIMARY"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "11/02/2010 GENERAL"), "2010/11/02 GENERAL"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "11/04/2014 GENERAL"), "2014/11/04 GENERAL"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "11/06/2012 GENERAL"), "2012/11/06 GENERAL"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "11/08/2016 GENERAL"), "2016/11/08 GENERAL"))

reg_voters <- reg_voters %>%
        mutate(subtype = replace(subtype, str_detect(subtype, "White"), "White, non-Hispanic")) %>%
        mutate(election.name = replace(election.name, str_detect(election.name, "11/04/2008 GENERAL"), "2008/11/04 GENERAL"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "03/15/2016 PRIMARY"), "2016/03/15 PRIMARY"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "05/04/2010 PRIMARY"), "2010/05/04 PRIMARY"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "05/06/2014 PRIMARY"), "2014/05/06 PRIMARY"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "05/08/2012 PRIMARY"), "2012/05/08 PRIMARY"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "11/02/2010 GENERAL"), "2010/11/02 GENERAL"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "11/04/2014 GENERAL"), "2014/11/04 GENERAL"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "11/06/2012 GENERAL"), "2012/11/06 GENERAL"))%>% 
        mutate(election.name = replace(election.name, str_detect(election.name, "11/08/2016 GENERAL"), "2016/11/08 GENERAL"))

write_csv(tableau_data,'data/tableau_data.csv')

```

------


```{r}
# bar chart of ethnicity with all geographies in the most recent year
all %>%
  filter(type=='race')%>%
  # only keep most recent year
  ggplot(aes(election.name, pct_reg, fill=subtype)) +
  geom_bar(position = "dodge", stat='identity') +
  labs(title = paste0('Percent of registered voters that voted by election'),
       fill = 'Race/Ethnicity',
       y = 'Voter Participation Rate of Registered voters',
       x = '') +
  theme_minimal()
```

```{r}
all %>%
  filter(type=='race')%>%
  # only keep most recent year
  ggplot(aes(election.name, pct_eligible, fill=subtype)) +
  geom_bar(position = "dodge", stat='identity') +
  labs(title = paste0('Percent of eligible voters that voted by election'),
       fill = 'Race/Ethnicity',
       y = 'Voter Participation Rate of Eligible voters',
       x = '') +
  theme_minimal()
```


```{r}
# bar chart of race/ethnicity with all geographies in the most recent year
tableau_data %>%
  # only keep most recent year
  filter(type == 'race') %>%
  ggplot(aes(geography, estimate, fill=subtype)) +
    geom_bar(position = "dodge", stat='identity') +
    labs(title = paste0('Voter participation rate by race/ethnicity in 2016'),
         fill = 'Race/Ethnicity',
          y = 'Voter participation rate',
         x = '') +
    theme_minimal()
```


```{r}
# bar chart of age with all geographies in the most recent year
tableau_data %>%
  # only keep most recent year
  filter(type == 'age') %>%
  ggplot(aes(geography, estimate, fill=subtype)) +
    geom_bar(position = "dodge", stat='identity') +
    labs(title = paste0('Voter participation rate by age in 2016'),
         fill = 'Age Group',
          y = 'Voter participation rate',
         x = '') +
    theme_minimal()
```



```{r}
tableau_data %>%
  # only keep most recent year
  filter(type == 'gender') %>%
  ggplot(aes(geography, estimate, fill=subtype)) +
    geom_bar(position = "dodge", stat='identity') +
    labs(title = paste0('Voter participation rate by gender in 2016'),
         fill = 'Gender',
           y = 'Voter Participation Rate ',
         x = '') +
    theme_minimal()
```

```{r}
tableau_data %>%
  # only keep most recent year
  filter(type == 'ward', subtype != 'NA', subtype != '5') %>%
  ggplot(aes(geography, estimate, fill=subtype)) +
    geom_bar(position = "dodge", stat='identity') +
    labs(title = paste0('Voter participation rate by ward in 2016'),
         fill = 'ward',
           y = 'Voter Participation Rate ',
         x = '') +
    theme_minimal()
```


### Tableau dataset

This is the final data set that can be imported into Tableau. Users can copy it into an excel file or download a csv file.

```{r}
# estimates are percentages displayed in tens (60.45)
# convert to numbers to decimal percentages (.6045)
tableau_data %>%
  mutate_at(vars(estimate), funs(./100)) %>%
  # reorder column and do not include unneded columns
  select(year, geography, type, subtype, estimate) %>%
  # create table
  ff_data_dt(c('Year', 'Geographic area', 'Type', 'Subtype', 'Estimate'), for_tableau=TRUE)
``` 