#############################################################################
#
# Data calculations
#
# The following functions perform calculations on ACS data,
# such as adding proportions and conducting significance tests.
# change
##############################################################################


ff_acs_ratios <- function(df, num_estimate, num_moe, den_estimate, den_moe) {
  
  # This function calculates the ratios, se, and 95% margins of error for the ratios
  # The inputs are column names from the dataframe, entered as strings
  # The formula comes from:
  #    U.S. Census Bureau, A Compass for Understanding and Using ACS Survey Data, A-15
  #
  # The output is the same dataframe with the ratio and margin of error added to the dataframe
  
  # calculate the ratio
  ratio  <- df[[num_estimate]] / df[[den_estimate]]
  
  # calculate the numerator for the MOE formula
  moe_num <- sqrt(df[[num_moe]]^2 + (ratio^2 * df[[den_moe]]^2))
  
  # calculate MOE
  moe <- moe_num / df[[den_estimate]]
  
  # calcuate standard error
  # note: since 95% confidence intervals are used, the moe is divided
  # by 1.96, not 1.645 when using the 90% moe's from AFF
  se <- moe / 1.96
  
  # add ratio, MOE, and se to dataframe
  df$ratio <- ratio
  df$ratio_moe <- moe
  df$ratio_se <- se
  
  return(df)
  
}



ff_acs_zscore <- function(data_frame, estimate, se, var_names = NULL) {
  
  # This function returns a square symetrical matrix of z scores for all combinations of values
  # The matrix length and with equal the number of rows in the data frame
  #
  # The formula comes from:
  #    U.S. Census Bureau, A Compass for Understanding and Using ACS Survey Data, A-18
  #
  # Parameters:
  #   data_frame: the dataframe where the estimates and se are housed
  #   estimate: a string that is the column name of the column containing the estimate
  #   se: a string that is the column name of the column containing the se
  #   var_names: a character vector of variables that can be combined to created
  #              distinct names for each row and column
  
  
  # initialize an empty data frame with one column and the same number
  # of rows as the final dataframe
  z_score_mat <- data.frame(n = seq(1, nrow(data_frame)))
  
  # iterate through each row in the dataframe
  for (i in 1:nrow(data_frame)) {
    
    # calculate the point estimate differences and the sum of
    # of standard errors for the given row and all other rows
    # this will return a vector
    estimate_diff <- data_frame[[i, estimate]] - data_frame[[estimate]]
    se_diff <- sqrt( data_frame[[i, se]]^2 + data_frame[[se]]^2 )
    
    # calculate the z score for all row values, rounds to two decimals
    z_score <- abs( estimate_diff / se_diff) %>% round(2)

    # add the row of z scores to the z score matrix
    z_score_mat[, i] <- z_score
    
  }
  
  if (!is.null(var_names)) {
    
    # create vector of label names by pasting columns together
    names_vec <- apply( data_frame[ , var_names], 1, paste, collapse = "-" )
    
    # add labels as column and row names
    colnames(z_score_mat) <- names_vec
    row.names(z_score_mat) <- names_vec
    
  }
  
  return(z_score_mat)
  
}


ff_acs_zsignif <- function(zscore_matrix) {
  
  # This function takes as input a matrix of z score generated by ff_acs_zscore
  # it returns a matrix of the same size with the value of TRUE if the z score
  # is statistically significant at 95%, and false otherwise
  
  # conduct boolean test of whether value is greater than 1.96
  z_significance <- zscore_matrix %>%
    mutate_all(funs(. > 1.96))
  
  return(z_significance)
  
}


ff_acs_zplot <- function(zscore_matrix) {
  
  # This function returns a plot similair to a correlatin plot,
  # showing whether z values are significant
  # Its input is a z sore matrix generated from ff_acs_zscore

  # identify column names of first and last columns, so they can be used to gather data
  first <- names(zscore_matrix[1])
  last <- names(zscore_matrix[ncol(zscore_matrix)])
  
  # add column of row names to matrix
  zscore_matrix$row_names <- row.names(zscore_matrix)
  
  # gather values to create long form data set
  zscore_matrix %>% gather(first:last, key = 'var1', value = 'value') %>%
  # plot
  ggplot(aes(row_names, var1, fill = value))+
    geom_tile(color = "white")+
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                         midpoint = 1.96, space = "Lab",
                         name="Z-Score Matrix\nBlue < 1.96\nRed > 1.96") +
    labs(title = 'Z score significance',
         x = '', y = '') +
    theme_minimal()+ 
    theme(axis.text.x = element_text(angle = 90, vjust = 1, 
                                     size = 12, hjust = 1))+
    coord_fixed()

}