---
title: "Income Quintiles"
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---

```{r setup, include=FALSE}
# set value of whether the file is for an analyst, and therefore all resutls and code blocks are needed,
# or whether the file is for another, and some results and all code blocks are hidden
for_analyst <- TRUE

# global options for code blocks
knitr::opts_chunk$set(warning = FALSE, # supress warnings
                      message = FALSE, # supress messages
                      # do not print out code blocks if for_analyst equals FALSE 
                      echo = FALSE)
                      #echo = ifelse(for_analyst == FALSE, FALSE, TRUE))

# value that sets the 'include' parameter in Markdown based on whether the document is for the analyst
to_include = ifelse(for_analyst == TRUE, TRUE, FALSE)
```

```{r import}
 # import functions and packages
library(tidyverse)
library(knitr)
library(tidycensus)
library(DT)
# load custom ACS functions
source('../../functions/acs_load_funcs.R')
```

Income quintile data comes from the following AFF table:

* B19080

**All income quintiles and corresponding standard errors and margins of error were adjusted to 2017 dollars.**

### Data cleaning

This code block imports and cleans the data. 

```{r}
df <- read_csv('data/income_quintiles_all_years_counties.csv') %>%
  ff_inflation_adjust(estimate, se, 2017, error = TRUE) %>%
  # delete columns with non-adjusted data, and replace them with columns of adjusted data
  select(-estimate, -cv, -moe, -se, -'0') %>%
  # rename adjusted columns to match naming in original columns
  rename(estimate = estimate_adj,
         moe = moe_adj,
         se = se_adj,
         cv = cv_adj) %>% 
  mutate(description = ifelse((str_detect(description,'Lowest')),'Q1', 
                                ifelse((str_detect(description,'Second')),'Q2',
                                       ifelse((str_detect(description,'Third')),'Q3',
                                              ifelse((str_detect(description,'Fourth')), 'Q4', 'Q5'))))) 

  
#write_csv(df, 'C:/Users/mjoan/OneDrive/Documents/indicators/i_economic/income_quintiles/AFF_income_quintiles_shiny/AFF_income_quintiles.csv')
                     

```

------

### Forsyth County year-to-year trends

#### Plot

The plot below shows the yearly income quintiles trends for Forsyth County. 

```{r}
df %>%
  mutate(description = ifelse((str_detect(description,'Q1')),'20th Percentile', 
                                ifelse((str_detect(description,'Q2')),'40th Percentile',
                                       ifelse((str_detect(description,'Q3')),'60th Percentile',
                                              ifelse((str_detect(description,'Q4')), '80th Percentile', '95th Percentile'))))) %>%
  filter(geo_description == 'Forsyth County, NC') %>%
  ggplot(aes(year, estimate, color = description)) +
    geom_line(size = 1) +
    labs(title = 'Forsyth County Income Quintiles',
         color = 'Comparison Unit',
         y = 'Income') +
    scale_x_continuous(breaks = seq(min(df$year), max(df$year), 1),
                       minor_breaks = NULL) +
    theme_minimal()
```


#### Interpretation

* 
*


#### Z-scores

The table below lists yearly and income quintile z-scores for Forsyth County.

```{r include = to_include}
df %>%
  # only keep data for the most recent year
  filter(geo_description == 'Forsyth County, NC') %>%
  ff_acs_zscore_dt('estimate', 'se', c('year','description'))
         
```

### Community Comparisons by Income Quintile

### Q1 Plot

```{r}
df %>%
  filter(description == 'Q1') %>%
  ggplot(aes(year, estimate, color = geo_description)) +
    geom_line(size = 1) +
    labs(title = '20th Percentile (Q1)',
         color = 'Comparison Unit',
         y = 'Income') +
    scale_x_continuous(breaks = seq(min(df$year), max(df$year), 1),
                       minor_breaks = NULL) +
    theme_minimal()
```

#### Interpretation

* 
*

### Q2 Plot

```{r}
df %>%
  filter(description == 'Q2') %>%
  ggplot(aes(year, estimate, color = geo_description)) +
    geom_line(size = 1) +
    labs(title = '40th Percentile (Q2)',
         color = 'Comparison Unit',
         y = 'Income') +
    scale_x_continuous(breaks = seq(min(df$year), max(df$year), 1),
                       minor_breaks = NULL) +
    theme_minimal()
```

#### Interpretation

* 
*

### Q3 Plot

```{r}
df %>%
  filter(description == 'Q3') %>%
  ggplot(aes(year, estimate, color = geo_description)) +
    geom_line(size = 1) +
    labs(title = '60th Percentile (Q3)',
         color = 'Comparison Unit',
         y = 'Income') +
    scale_x_continuous(breaks = seq(min(df$year), max(df$year), 1),
                       minor_breaks = NULL) +
    theme_minimal()
```

#### Interpretation

* 
*

### Q4 Plot

```{r}
df %>%
  filter(description == 'Q4') %>%
  ggplot(aes(year, estimate, color = geo_description)) +
    geom_line(size = 1) +
    labs(title = '80th Percentile (Q4)',
         color = 'Comparison Unit',
         y = 'Income') +
    scale_x_continuous(breaks = seq(min(df$year), max(df$year), 1),
                       minor_breaks = NULL) +
    theme_minimal()
```

#### Interpretation

* 
*

### Q5 Plot

```{r}
df %>%
  filter(description == 'Q5') %>%
  ggplot(aes(year, estimate, color = geo_description)) +
    geom_line(size = 1) +
    labs(title = '95th Percentile (Lower Limit of Top 5%)',
         color = 'Comparison Unit',
         y = 'Income') +
    scale_x_continuous(breaks = seq(min(df$year), max(df$year), 1),
                       minor_breaks = NULL) +
    theme_minimal()
```

#### Interpretation

* 
*


### All Quintiles Data

Below is the raw data for income quintiles by geographies.

```{r include = to_include}
total_data <- df %>%
 select(geo_description, year, description, estimate, moe, se, cv)

# this represents the final dataset that will be sent to others for visualizations
tableau_data <- total_data %>%
  # add type of column
  mutate(type = 'Comparison Community',
         subtype = 'Total Population')

ff_data_dt(total_data,
           c('Geographic area', 'Year', 'Quintile', 'Income', '95% MOE', 'St. Error', 'CV'))
```

#### Z-scores

The table below shows z-scores of all comparison communities for the past two years. To change the comparison year, replace the `c(max(df$year), max(df$year)-1)` segment of `year_comparison <- max(df$year)` with the desired year or vector of years such as `c(2013, 2014, 2015)`.

```{r include = to_include}
year_comparison <- c(2006:2017)

df %>%
  # only keep total employment rate
  filter(year %in% year_comparison) %>%
  ff_acs_zscore_dt('estimate', 'se', c('geo_description', 'year','description'))
```

------

### Tableau dataset

This is the final data set that can be imported into Tableau. Users can copy it into an excel file or download a csv file.

```{r}
# create table to Tableau data
tableau_data %>%
  select(year, geo_description, type, subtype, description, estimate) %>%
  # removes rows containing demographic data for comparison communities 
  # in all years except the latest year
  ff_remove_comparisons() %>%
  # create table
  ff_data_dt(c('Year', 'Geographic area', 'Type', 'Subtype', 'Quintile', 'Estimate'), for_tableau=TRUE)
```